added password hashing
yutsevich/internet-shop pull request #14
Opened 2020-09-29 09:16 UTC by yutsevich

2020-09-29 09:35 UTC, andriylagun commented on src/main/java/com/internet/shop/controllers/RegistrationController.java
> +            user.setSalt(salt);
Let's implement this logic in service layer

2020-09-29 09:35 UTC, andriylagun commented on src/main/java/com/internet/shop/util/HashUtil.java
> +    }
why do you need this method if you don't use it? And do you sure that u need logic for hashing in check method?

2020-09-29 17:01 UTC, KseniiaMakarova requested changes

2020-09-29 17:01 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/dao/mysqlimpl/UserDaoJdbcImpl.java
> +            statement.setBytes(4, user.getSalt());
should we also set userId?

2020-09-29 17:01 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/security/AuthenticationServiceImpl.java
> +                        .equals(user.get().getPassword())) {
```suggestion
        if (user.isEmpty() || !isPasswordValid(user.get(), password)) {
```
let's create a private method here with this logic

2020-09-29 17:01 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/util/HashUtil.java
> +            e.printStackTrace();
let's throw a RuntimeException instead

2020-09-29 19:15 UTC, yutsevich commented on src/main/java/com/internet/shop/dao/mysqlimpl/UserDaoJdbcImpl.java
> +            statement.setBytes(4, user.getSalt());
no, it should be same because method finds user by id

2020-09-30 06:56 UTC, KseniiaMakarova requested changes

2020-09-30 06:56 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/dao/mysqlimpl/UserDaoJdbcImpl.java
> +            statement.setBytes(4, user.getSalt());
you have a query with 5 `?` pieces of data that should be set if we want the statement to work properly
lI can see that you set only the first four

2020-09-30 06:56 UTC, KseniiaMakarova commented on src/main/java/com/internet/shop/util/HashUtil.java
> +            throw new RuntimeException();
let's put an informative message here and also pass the original exception (`e`)

2020-09-30 07:36 UTC, KseniiaMakarova approved these changes

2020-09-30 09:22 UTC, merged